---
- name: Simple Perf Test 
  hosts: localhost
  connection: local
  #  gather_facts: false

  vars:
    api: ""
    token: ""
    test_image: "nginx:latest" 
    cluster_name: ""
    pod_test:
      enabled: true
      pod_cnt: 50 
    pg:
      host: localhost
      port: 5432
      db: postgres 
      user: 
      pass: 

  tasks:
  - name: Create a k8s namespace for test
    community.kubernetes.k8s:
      validate_certs: no 
      host: "{{ api }}"
      api_key: "{{ token }}"
      name: "test-xyz"
      api_version: v1
      kind: Namespace
      state: present 
    register: ns

  - name: Start Pod to Load image
    community.kubernetes.k8s:
      validate_certs: no 
      host: "{{ api }}"
      api_key: "{{ token }}"
      state: present
      template: pod-single.j2
      wait: true
    when: ns.changed

  - name: Stop Pod to Load image
    community.kubernetes.k8s:
      validate_certs: no 
      host: "{{ api }}"
      api_key: "{{ token }}"
      state: absent 
      template: pod-single.j2
      wait: true
    when: ns.changed

  - name: Start "{{ pod_cnt }}" pods 
    community.kubernetes.k8s:
      validate_certs: no 
      host: "{{ api }}"
      api_key: "{{ token }}"
      state: present
      template: pod.j2
      wait: false
    register: pod_start 

  - pause:
      seconds: 60
    when: pod_start.changed

  - name: Search for all Pods 
    community.kubernetes.k8s_info:
      validate_certs: no 
      host: "{{ api }}"
      api_key: "{{ token }}"
      namespace: test-xyz
      kind: Pod
      label_selectors:
        - perf-test = true
    register: pod_info

  - name: print result info
    template:
      src: pod_result_insert.j2 
      dest: /tmp/results.csv 

  - name: Insert Results to postgres DB 
    community.postgresql.postgresql_query:
      db: "{{ pg.db }}" 
      login_host: "{{ pg.host }}"
      login_port: "{{ pg.port }}" 
      login_user: "{{ pg.user }}" 
      login_password: "{{ pg.pass }}"
      path_to_script: results.sql
      as_single_query: true
      search_path:
        - perftest
